export const REAL_COURSE_SCHEDULE = [
  {
    "date": "2026-06-16",
    "weekday": "星期二",
    "title": "大模型开发入门V4.0",
    "course_type": "lecture",
    "start_time": "19:25",
    "end_time": "22:30",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-06-17",
    "weekday": "星期三",
    "title": "大模型开发入门V4.0",
    "course_type": "lecture",
    "start_time": "19:25",
    "end_time": "22:30",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-06-20",
    "weekday": "星期六",
    "title": "大模型开发入门V4.0",
    "course_type": "lecture",
    "start_time": "19:25",
    "end_time": "22:30",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-06-21",
    "weekday": "星期日",
    "title": "大模型开发入门V4.0",
    "course_type": "lecture",
    "start_time": "19:25",
    "end_time": "22:30",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-06-22",
    "weekday": "星期一",
    "title": "自习",
    "course_type": "self_study",
    "start_time": "10:00",
    "end_time": "12:00",
    "description": null,
    "is_rest": 0,
    "is_self_study": 1
  },
  {
    "date": "2026-06-22",
    "weekday": "星期一",
    "title": "自习",
    "course_type": "self_study",
    "start_time": "14:00",
    "end_time": "17:00",
    "description": null,
    "is_rest": 0,
    "is_self_study": 1
  },
  {
    "date": "2026-06-23",
    "weekday": "星期二",
    "title": "大模型开发入门V4.0",
    "course_type": "lecture",
    "start_time": "08:30",
    "end_time": "12:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-06-23",
    "weekday": "星期二",
    "title": "大模型开发入门V4.0",
    "course_type": "lecture",
    "start_time": "14:30",
    "end_time": "18:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-06-23",
    "weekday": "星期二",
    "title": "大模型开发入门V4.0",
    "course_type": "lecture",
    "start_time": "19:25",
    "end_time": "22:30",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-06-24",
    "weekday": "星期三",
    "title": "大模型开发入门V4.0",
    "course_type": "lecture",
    "start_time": "08:30",
    "end_time": "12:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-06-24",
    "weekday": "星期三",
    "title": "大模型开发入门V4.0",
    "course_type": "lecture",
    "start_time": "14:30",
    "end_time": "18:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-06-24",
    "weekday": "星期三",
    "title": "大模型开发入门V4.0",
    "course_type": "lecture",
    "start_time": "19:25",
    "end_time": "22:30",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-06-25",
    "weekday": "星期四",
    "title": "休息",
    "course_type": "rest",
    "start_time": null,
    "end_time": null,
    "description": null,
    "is_rest": 1,
    "is_self_study": 0
  },
  {
    "date": "2026-06-26",
    "weekday": "星期五",
    "title": "大模型开发入门V4.0",
    "course_type": "lecture",
    "start_time": "08:30",
    "end_time": "12:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-06-26",
    "weekday": "星期五",
    "title": "大模型开发入门V4.0",
    "course_type": "lecture",
    "start_time": "14:30",
    "end_time": "18:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-06-26",
    "weekday": "星期五",
    "title": "大模型开发入门V4.0",
    "course_type": "lecture",
    "start_time": "19:25",
    "end_time": "22:30",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-06-27",
    "weekday": "星期六",
    "title": "大模型开发入门V4.0",
    "course_type": "lecture",
    "start_time": "08:30",
    "end_time": "12:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-06-27",
    "weekday": "星期六",
    "title": "大模型开发入门V4.0",
    "course_type": "lecture",
    "start_time": "14:30",
    "end_time": "18:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-06-27",
    "weekday": "星期六",
    "title": "大模型开发入门V4.0",
    "course_type": "lecture",
    "start_time": "19:25",
    "end_time": "22:30",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-06-28",
    "weekday": "星期日",
    "title": "自习",
    "course_type": "self_study",
    "start_time": "10:00",
    "end_time": "12:00",
    "description": null,
    "is_rest": 0,
    "is_self_study": 1
  },
  {
    "date": "2026-06-28",
    "weekday": "星期日",
    "title": "自习",
    "course_type": "self_study",
    "start_time": "14:00",
    "end_time": "17:00",
    "description": null,
    "is_rest": 0,
    "is_self_study": 1
  },
  {
    "date": "2026-06-29",
    "weekday": "星期一",
    "title": "大模型语言进阶V4.0",
    "course_type": "lecture",
    "start_time": "08:30",
    "end_time": "12:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-06-29",
    "weekday": "星期一",
    "title": "大模型语言进阶V4.0",
    "course_type": "lecture",
    "start_time": "14:30",
    "end_time": "18:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-06-29",
    "weekday": "星期一",
    "title": "大模型语言进阶V4.0",
    "course_type": "lecture",
    "start_time": "19:25",
    "end_time": "22:30",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-06-30",
    "weekday": "星期二",
    "title": "大模型语言进阶V4.0",
    "course_type": "lecture",
    "start_time": "08:30",
    "end_time": "12:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-06-30",
    "weekday": "星期二",
    "title": "大模型语言进阶V4.0",
    "course_type": "lecture",
    "start_time": "14:30",
    "end_time": "18:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-06-30",
    "weekday": "星期二",
    "title": "大模型语言进阶V4.0",
    "course_type": "lecture",
    "start_time": "19:25",
    "end_time": "22:30",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-01",
    "weekday": "星期三",
    "title": "休息",
    "course_type": "rest",
    "start_time": null,
    "end_time": null,
    "description": null,
    "is_rest": 1,
    "is_self_study": 0
  },
  {
    "date": "2026-07-02",
    "weekday": "星期四",
    "title": "大模型开发入门V4.0",
    "course_type": "lecture",
    "start_time": "08:30",
    "end_time": "12:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-02",
    "weekday": "星期四",
    "title": "大模型开发入门V4.0",
    "course_type": "lecture",
    "start_time": "14:30",
    "end_time": "18:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-02",
    "weekday": "星期四",
    "title": "大模型开发入门V4.0",
    "course_type": "lecture",
    "start_time": "19:25",
    "end_time": "22:30",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-03",
    "weekday": "星期五",
    "title": "大模型开发入门V4.0",
    "course_type": "lecture",
    "start_time": "08:30",
    "end_time": "12:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-03",
    "weekday": "星期五",
    "title": "大模型开发入门V4.0",
    "course_type": "lecture",
    "start_time": "14:30",
    "end_time": "18:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-03",
    "weekday": "星期五",
    "title": "大模型开发入门V4.0",
    "course_type": "lecture",
    "start_time": "19:25",
    "end_time": "22:30",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-04",
    "weekday": "星期六",
    "title": "自习",
    "course_type": "self_study",
    "start_time": "10:00",
    "end_time": "12:00",
    "description": null,
    "is_rest": 0,
    "is_self_study": 1
  },
  {
    "date": "2026-07-04",
    "weekday": "星期六",
    "title": "自习",
    "course_type": "self_study",
    "start_time": "14:00",
    "end_time": "17:00",
    "description": null,
    "is_rest": 0,
    "is_self_study": 1
  },
  {
    "date": "2026-07-05",
    "weekday": "星期日",
    "title": "大模型语言进阶V4.0",
    "course_type": "lecture",
    "start_time": "08:30",
    "end_time": "12:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-05",
    "weekday": "星期日",
    "title": "大模型语言进阶V4.0",
    "course_type": "lecture",
    "start_time": "14:30",
    "end_time": "18:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-05",
    "weekday": "星期日",
    "title": "大模型语言进阶V4.0",
    "course_type": "lecture",
    "start_time": "19:25",
    "end_time": "22:30",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-06",
    "weekday": "星期一",
    "title": "大模型语言进阶V4.0",
    "course_type": "lecture",
    "start_time": "08:30",
    "end_time": "12:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-06",
    "weekday": "星期一",
    "title": "大模型语言进阶V4.0",
    "course_type": "lecture",
    "start_time": "14:30",
    "end_time": "18:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-06",
    "weekday": "星期一",
    "title": "大模型语言进阶V4.0",
    "course_type": "lecture",
    "start_time": "19:25",
    "end_time": "22:00",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-07",
    "weekday": "星期二",
    "title": "休息",
    "course_type": "rest",
    "start_time": null,
    "end_time": null,
    "description": null,
    "is_rest": 1,
    "is_self_study": 0
  },
  {
    "date": "2026-07-08",
    "weekday": "星期三",
    "title": "大模型开发入门V4.0",
    "course_type": "lecture",
    "start_time": "08:30",
    "end_time": "12:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-08",
    "weekday": "星期三",
    "title": "大模型开发入门V4.0",
    "course_type": "lecture",
    "start_time": "14:30",
    "end_time": "18:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-08",
    "weekday": "星期三",
    "title": "大模型开发入门V4.0",
    "course_type": "lecture",
    "start_time": "19:25",
    "end_time": "22:30",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-09",
    "weekday": "星期四",
    "title": "大模型开发入门V4.0",
    "course_type": "lecture",
    "start_time": "08:30",
    "end_time": "12:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-09",
    "weekday": "星期四",
    "title": "大模型开发入门V4.0",
    "course_type": "lecture",
    "start_time": "14:30",
    "end_time": "18:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-09",
    "weekday": "星期四",
    "title": "大模型开发入门V4.0",
    "course_type": "lecture",
    "start_time": "19:25",
    "end_time": "22:30",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-10",
    "weekday": "星期五",
    "title": "自习",
    "course_type": "self_study",
    "start_time": "10:00",
    "end_time": "12:00",
    "description": null,
    "is_rest": 0,
    "is_self_study": 1
  },
  {
    "date": "2026-07-10",
    "weekday": "星期五",
    "title": "自习",
    "course_type": "self_study",
    "start_time": "14:00",
    "end_time": "17:00",
    "description": null,
    "is_rest": 0,
    "is_self_study": 1
  },
  {
    "date": "2026-07-11",
    "weekday": "星期六",
    "title": "大模型语言进阶V4.0",
    "course_type": "lecture",
    "start_time": "08:30",
    "end_time": "12:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-11",
    "weekday": "星期六",
    "title": "大模型语言进阶V4.0",
    "course_type": "lecture",
    "start_time": "14:30",
    "end_time": "18:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-11",
    "weekday": "星期六",
    "title": "大模型语言进阶V4.0",
    "course_type": "lecture",
    "start_time": "19:25",
    "end_time": "22:30",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-12",
    "weekday": "星期日",
    "title": "休息",
    "course_type": "rest",
    "start_time": null,
    "end_time": null,
    "description": null,
    "is_rest": 1,
    "is_self_study": 0
  },
  {
    "date": "2026-07-13",
    "weekday": "星期一",
    "title": "大模型语言进阶V4.0",
    "course_type": "lecture",
    "start_time": "08:30",
    "end_time": "12:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-13",
    "weekday": "星期一",
    "title": "大模型语言进阶V4.0",
    "course_type": "lecture",
    "start_time": "14:30",
    "end_time": "18:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-13",
    "weekday": "星期一",
    "title": "大模型语言进阶V4.0",
    "course_type": "lecture",
    "start_time": "19:25",
    "end_time": "22:00",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-14",
    "weekday": "星期二",
    "title": "提示词工程",
    "course_type": "lecture",
    "start_time": "08:30",
    "end_time": "12:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-14",
    "weekday": "星期二",
    "title": "提示词工程",
    "course_type": "lecture",
    "start_time": "14:30",
    "end_time": "18:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-14",
    "weekday": "星期二",
    "title": "提示词工程",
    "course_type": "lecture",
    "start_time": "19:25",
    "end_time": "22:30",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-15",
    "weekday": "星期三",
    "title": "自习",
    "course_type": "self_study",
    "start_time": "10:00",
    "end_time": "12:00",
    "description": null,
    "is_rest": 0,
    "is_self_study": 1
  },
  {
    "date": "2026-07-15",
    "weekday": "星期三",
    "title": "自习",
    "course_type": "self_study",
    "start_time": "14:00",
    "end_time": "17:00",
    "description": null,
    "is_rest": 0,
    "is_self_study": 1
  },
  {
    "date": "2026-07-16",
    "weekday": "星期四",
    "title": "提示词工程",
    "course_type": "lecture",
    "start_time": "08:30",
    "end_time": "12:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-16",
    "weekday": "星期四",
    "title": "提示词工程",
    "course_type": "lecture",
    "start_time": "14:30",
    "end_time": "18:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-16",
    "weekday": "星期四",
    "title": "提示词工程",
    "course_type": "lecture",
    "start_time": "19:25",
    "end_time": "22:30",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-17",
    "weekday": "星期五",
    "title": "智能体开发(Coze+Dify)",
    "course_type": "lecture",
    "start_time": "08:30",
    "end_time": "12:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-17",
    "weekday": "星期五",
    "title": "智能体开发(Coze+Dify)",
    "course_type": "lecture",
    "start_time": "14:30",
    "end_time": "18:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-17",
    "weekday": "星期五",
    "title": "智能体开发(Coze+Dify)",
    "course_type": "lecture",
    "start_time": "19:25",
    "end_time": "22:30",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-18",
    "weekday": "星期六",
    "title": "休息",
    "course_type": "rest",
    "start_time": null,
    "end_time": null,
    "description": null,
    "is_rest": 1,
    "is_self_study": 0
  },
  {
    "date": "2026-07-19",
    "weekday": "星期日",
    "title": "智能体开发(Coze+Dify)",
    "course_type": "lecture",
    "start_time": "08:30",
    "end_time": "12:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-19",
    "weekday": "星期日",
    "title": "智能体开发(Coze+Dify)",
    "course_type": "lecture",
    "start_time": "14:30",
    "end_time": "18:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-19",
    "weekday": "星期日",
    "title": "智能体开发(Coze+Dify)",
    "course_type": "lecture",
    "start_time": "19:25",
    "end_time": "22:30",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-20",
    "weekday": "星期一",
    "title": "智能体开发(Coze+Dify)",
    "course_type": "lecture",
    "start_time": "08:30",
    "end_time": "12:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-20",
    "weekday": "星期一",
    "title": "智能体开发(Coze+Dify)",
    "course_type": "lecture",
    "start_time": "14:30",
    "end_time": "18:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-20",
    "weekday": "星期一",
    "title": "智能体开发(Coze+Dify)",
    "course_type": "lecture",
    "start_time": "19:25",
    "end_time": "22:30",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-21",
    "weekday": "星期二",
    "title": "自习",
    "course_type": "self_study",
    "start_time": "10:00",
    "end_time": "12:00",
    "description": null,
    "is_rest": 0,
    "is_self_study": 1
  },
  {
    "date": "2026-07-21",
    "weekday": "星期二",
    "title": "自习",
    "course_type": "self_study",
    "start_time": "14:00",
    "end_time": "17:00",
    "description": null,
    "is_rest": 0,
    "is_self_study": 1
  },
  {
    "date": "2026-07-22",
    "weekday": "星期三",
    "title": "智能体开发(Coze+Dify)",
    "course_type": "lecture",
    "start_time": "08:30",
    "end_time": "12:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-22",
    "weekday": "星期三",
    "title": "智能体开发(Coze+Dify)",
    "course_type": "lecture",
    "start_time": "14:30",
    "end_time": "18:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-22",
    "weekday": "星期三",
    "title": "智能体开发(Coze+Dify)",
    "course_type": "lecture",
    "start_time": "19:25",
    "end_time": "22:30",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-23",
    "weekday": "星期四",
    "title": "智能体开发(Coze+Dify)",
    "course_type": "lecture",
    "start_time": "08:30",
    "end_time": "12:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-23",
    "weekday": "星期四",
    "title": "智能体开发(Coze+Dify)",
    "course_type": "lecture",
    "start_time": "14:30",
    "end_time": "18:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-23",
    "weekday": "星期四",
    "title": "智能体开发(Coze+Dify)",
    "course_type": "lecture",
    "start_time": "19:25",
    "end_time": "22:30",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-24",
    "weekday": "星期五",
    "title": "休息",
    "course_type": "rest",
    "start_time": null,
    "end_time": null,
    "description": null,
    "is_rest": 1,
    "is_self_study": 0
  },
  {
    "date": "2026-07-25",
    "weekday": "星期六",
    "title": "智能体开发(Coze+Dify)",
    "course_type": "lecture",
    "start_time": "08:30",
    "end_time": "12:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-25",
    "weekday": "星期六",
    "title": "智能体开发(Coze+Dify)",
    "course_type": "lecture",
    "start_time": "14:30",
    "end_time": "18:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-25",
    "weekday": "星期六",
    "title": "智能体开发(Coze+Dify)",
    "course_type": "lecture",
    "start_time": "19:25",
    "end_time": "22:30",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-26",
    "weekday": "星期日",
    "title": "智能体开发(Coze+Dify)",
    "course_type": "lecture",
    "start_time": "08:30",
    "end_time": "12:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-26",
    "weekday": "星期日",
    "title": "智能体开发(Coze+Dify)",
    "course_type": "lecture",
    "start_time": "14:30",
    "end_time": "18:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-26",
    "weekday": "星期日",
    "title": "智能体开发(Coze+Dify)",
    "course_type": "lecture",
    "start_time": "19:25",
    "end_time": "22:30",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-27",
    "weekday": "星期一",
    "title": "自习",
    "course_type": "self_study",
    "start_time": "10:00",
    "end_time": "12:00",
    "description": null,
    "is_rest": 0,
    "is_self_study": 1
  },
  {
    "date": "2026-07-27",
    "weekday": "星期一",
    "title": "自习",
    "course_type": "self_study",
    "start_time": "14:00",
    "end_time": "17:00",
    "description": null,
    "is_rest": 0,
    "is_self_study": 1
  },
  {
    "date": "2026-07-28",
    "weekday": "星期二",
    "title": "智能体开发(Coze+Dify)",
    "course_type": "lecture",
    "start_time": "08:30",
    "end_time": "12:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-28",
    "weekday": "星期二",
    "title": "智能体开发(Coze+Dify)",
    "course_type": "lecture",
    "start_time": "14:30",
    "end_time": "18:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-28",
    "weekday": "星期二",
    "title": "智能体开发(Coze+Dify)",
    "course_type": "lecture",
    "start_time": "19:25",
    "end_time": "22:30",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-29",
    "weekday": "星期三",
    "title": "项目实战",
    "course_type": "lecture",
    "start_time": "08:30",
    "end_time": "12:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-29",
    "weekday": "星期三",
    "title": "项目实战",
    "course_type": "lecture",
    "start_time": "14:30",
    "end_time": "18:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-29",
    "weekday": "星期三",
    "title": "项目实战",
    "course_type": "lecture",
    "start_time": "19:25",
    "end_time": "22:30",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-30",
    "weekday": "星期四",
    "title": "休息",
    "course_type": "rest",
    "start_time": null,
    "end_time": null,
    "description": null,
    "is_rest": 1,
    "is_self_study": 0
  },
  {
    "date": "2026-07-31",
    "weekday": "星期五",
    "title": "大模型核心开发技术（ML）",
    "course_type": "lecture",
    "start_time": "08:30",
    "end_time": "12:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-31",
    "weekday": "星期五",
    "title": "大模型核心开发技术（ML）",
    "course_type": "lecture",
    "start_time": "14:30",
    "end_time": "18:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-07-31",
    "weekday": "星期五",
    "title": "大模型核心开发技术（ML）",
    "course_type": "lecture",
    "start_time": "19:25",
    "end_time": "22:30",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-08-01",
    "weekday": "星期六",
    "title": "大模型核心开发技术（ML）",
    "course_type": "lecture",
    "start_time": "08:30",
    "end_time": "12:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-08-01",
    "weekday": "星期六",
    "title": "大模型核心开发技术（ML）",
    "course_type": "lecture",
    "start_time": "14:30",
    "end_time": "18:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-08-01",
    "weekday": "星期六",
    "title": "大模型核心开发技术（ML）",
    "course_type": "lecture",
    "start_time": "19:25",
    "end_time": "22:30",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-08-02",
    "weekday": "星期日",
    "title": "自习",
    "course_type": "self_study",
    "start_time": "10:00",
    "end_time": "12:00",
    "description": null,
    "is_rest": 0,
    "is_self_study": 1
  },
  {
    "date": "2026-08-02",
    "weekday": "星期日",
    "title": "自习",
    "course_type": "self_study",
    "start_time": "14:00",
    "end_time": "17:00",
    "description": null,
    "is_rest": 0,
    "is_self_study": 1
  },
  {
    "date": "2026-08-03",
    "weekday": "星期一",
    "title": "大模型核心开发技术（ML）",
    "course_type": "lecture",
    "start_time": "08:30",
    "end_time": "12:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-08-03",
    "weekday": "星期一",
    "title": "大模型核心开发技术（ML）",
    "course_type": "lecture",
    "start_time": "14:30",
    "end_time": "18:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-08-03",
    "weekday": "星期一",
    "title": "大模型核心开发技术（ML）",
    "course_type": "lecture",
    "start_time": "19:25",
    "end_time": "22:30",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-08-04",
    "weekday": "星期二",
    "title": "大模型核心开发技术（ML）",
    "course_type": "lecture",
    "start_time": "08:30",
    "end_time": "12:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-08-04",
    "weekday": "星期二",
    "title": "大模型核心开发技术（ML）",
    "course_type": "lecture",
    "start_time": "14:30",
    "end_time": "18:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-08-04",
    "weekday": "星期二",
    "title": "大模型核心开发技术（ML）",
    "course_type": "lecture",
    "start_time": "19:25",
    "end_time": "22:30",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-08-05",
    "weekday": "星期三",
    "title": "休息",
    "course_type": "rest",
    "start_time": null,
    "end_time": null,
    "description": null,
    "is_rest": 1,
    "is_self_study": 0
  },
  {
    "date": "2026-08-06",
    "weekday": "星期四",
    "title": "大模型核心开发技术（ML）",
    "course_type": "lecture",
    "start_time": "08:30",
    "end_time": "12:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-08-06",
    "weekday": "星期四",
    "title": "大模型核心开发技术（ML）",
    "course_type": "lecture",
    "start_time": "14:30",
    "end_time": "18:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-08-06",
    "weekday": "星期四",
    "title": "大模型核心开发技术（ML）",
    "course_type": "lecture",
    "start_time": "19:25",
    "end_time": "22:30",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-08-07",
    "weekday": "星期五",
    "title": "大模型核心开发技术（DL）",
    "course_type": "lecture",
    "start_time": "08:30",
    "end_time": "12:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-08-07",
    "weekday": "星期五",
    "title": "大模型核心开发技术（DL）",
    "course_type": "lecture",
    "start_time": "14:30",
    "end_time": "18:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-08-07",
    "weekday": "星期五",
    "title": "大模型核心开发技术（DL）",
    "course_type": "lecture",
    "start_time": "19:25",
    "end_time": "22:30",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-08-08",
    "weekday": "星期六",
    "title": "自习",
    "course_type": "self_study",
    "start_time": "10:00",
    "end_time": "12:00",
    "description": null,
    "is_rest": 0,
    "is_self_study": 1
  },
  {
    "date": "2026-08-08",
    "weekday": "星期六",
    "title": "自习",
    "course_type": "self_study",
    "start_time": "14:00",
    "end_time": "17:00",
    "description": null,
    "is_rest": 0,
    "is_self_study": 1
  },
  {
    "date": "2026-08-09",
    "weekday": "星期日",
    "title": "大模型核心开发技术（DL）",
    "course_type": "lecture",
    "start_time": "08:30",
    "end_time": "12:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-08-09",
    "weekday": "星期日",
    "title": "大模型核心开发技术（DL）",
    "course_type": "lecture",
    "start_time": "14:30",
    "end_time": "18:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-08-09",
    "weekday": "星期日",
    "title": "大模型核心开发技术（DL）",
    "course_type": "lecture",
    "start_time": "19:25",
    "end_time": "22:30",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-08-10",
    "weekday": "星期一",
    "title": "休息",
    "course_type": "rest",
    "start_time": null,
    "end_time": null,
    "description": null,
    "is_rest": 1,
    "is_self_study": 0
  },
  {
    "date": "2026-08-11",
    "weekday": "星期二",
    "title": "大模型核心开发技术（DL）",
    "course_type": "lecture",
    "start_time": "08:30",
    "end_time": "12:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-08-11",
    "weekday": "星期二",
    "title": "大模型核心开发技术（DL）",
    "course_type": "lecture",
    "start_time": "14:30",
    "end_time": "18:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-08-11",
    "weekday": "星期二",
    "title": "大模型核心开发技术（DL）",
    "course_type": "lecture",
    "start_time": "19:25",
    "end_time": "22:30",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-08-12",
    "weekday": "星期三",
    "title": "大模型核心开发技术（DL）",
    "course_type": "lecture",
    "start_time": "08:30",
    "end_time": "12:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-08-12",
    "weekday": "星期三",
    "title": "大模型核心开发技术（DL）",
    "course_type": "lecture",
    "start_time": "14:30",
    "end_time": "18:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-08-12",
    "weekday": "星期三",
    "title": "大模型核心开发技术（DL）",
    "course_type": "lecture",
    "start_time": "19:25",
    "end_time": "22:30",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-08-13",
    "weekday": "星期四",
    "title": "自习",
    "course_type": "self_study",
    "start_time": "10:00",
    "end_time": "12:00",
    "description": null,
    "is_rest": 0,
    "is_self_study": 1
  },
  {
    "date": "2026-08-13",
    "weekday": "星期四",
    "title": "自习",
    "course_type": "self_study",
    "start_time": "14:00",
    "end_time": "17:00",
    "description": null,
    "is_rest": 0,
    "is_self_study": 1
  },
  {
    "date": "2026-08-14",
    "weekday": "星期五",
    "title": "大模型核心开发技术（DL）",
    "course_type": "lecture",
    "start_time": "08:30",
    "end_time": "12:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-08-14",
    "weekday": "星期五",
    "title": "大模型核心开发技术（DL）",
    "course_type": "lecture",
    "start_time": "14:30",
    "end_time": "18:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-08-14",
    "weekday": "星期五",
    "title": "大模型核心开发技术（DL）",
    "course_type": "lecture",
    "start_time": "19:25",
    "end_time": "22:30",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-08-15",
    "weekday": "星期六",
    "title": "大模型核心开发技术（DL）",
    "course_type": "lecture",
    "start_time": "08:30",
    "end_time": "12:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-08-15",
    "weekday": "星期六",
    "title": "大模型核心开发技术（DL）",
    "course_type": "lecture",
    "start_time": "14:30",
    "end_time": "18:20",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  },
  {
    "date": "2026-08-15",
    "weekday": "星期六",
    "title": "大模型核心开发技术（DL）",
    "course_type": "lecture",
    "start_time": "19:25",
    "end_time": "22:30",
    "description": null,
    "is_rest": 0,
    "is_self_study": 0
  }
]
